### ISSUE TITLE
radiothek search results can't be played

### ISSUE THREAD

**Issue by DButter** [s0faking/plugin.audio.radiothek#1]
Using the radiothek search results in strange stream links that cannot be opened. Using Kore remote for Input.

f.e.: i searched Kurt Nekula über das Down-Syndrom from 22.03.2019 at 0655 and my initial result looked good, but when i clicked it i got redirected to a no playable link.

also there seem to be some errounous default results called "kore_dummy_input", so maybe there is some compatibility issue between kore and kodi at fault here.

**Comment by DButter** [comment]
I just tried it with Wochenendplaylist and the behaviour is identical.

search returns good looking result, clicking on it leads you to a number of stream links that wont work and/or have nothing to do with the initial result.

**Comment by s0faking** [comment]
i just tried this and it works fine on my test system. can you post a debug log? 

can you name the unrelated items that are listed when clicking on "wochenendplaylist" for example?

**Comment by DButter** [comment]
hi, 
thank you for answering :)

webinterface before searching:

![search_b4](https://user-images.githubusercontent.com/14800832/77688435-5f260880-6fa0-11ea-9369-0894066049ca.PNG)

query:

![search_query](https://user-images.githubusercontent.com/14800832/77688482-6ea55180-6fa0-11ea-80ad-b35a20685068.PNG)

first result:

![search_first_result](https://user-images.githubusercontent.com/14800832/77688511-7a911380-6fa0-11ea-9253-ee4b12c7b176.PNG)

after clicking 22.03:

![search_second_result](https://user-images.githubusercontent.com/14800832/77688544-8977c600-6fa0-11ea-897a-1394d6c55159.PNG)

none of these actually do anything

if you want any logfiles you'd have to tell where they are. i can access my kodi via ssh, so there shouldnt be any problems getting there, but Ive no idea where the relevant logfiles are

**Comment by s0faking** [comment]
hm this might be a webinterface issue maybe. does the same thing happen when you are using kodi directly? if you don't have a remote i think there is a remote option on the webinterface to use the arrow keys and select key. i get the same results and the audio tracks are playing fine (it takes a bit longer to load since everyone is sitting at home now i guess ;)). you can send me the logfile using this addon: https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader. don't forget to enable debug logging before. check this manual for more info: https://kodi.wiki/view/Log_file/Easy

**Comment by DButter** [comment]
just tried it directly, same result :(

working on the logfile

**Comment by s0faking** [comment]
just tested this on my system with the webinterface. works fine too. i realised you have to double click the items to start them. also the webinterface creates kind of a delay because of the json communication with the core. the actions are probably queued on the json worker and executed after a few seconds. oh, and i saw that the remote control on the webinterface is gone. so you might need a remote. keyboard will do fine too i guess

**Comment by DButter** [comment]
actually im trying to use kodi as a headless radio :D 

double clicking doesnt do anything, but upping the loglevel is really killing my raspi

**Comment by DButter** [comment]
https://paste.kodi.tv/ugitenibeg.kodi

i hope this is ok as well

**Comment by DButter** [comment]
but i dont know how relevant these logs are, the behaviour totally changed after setting it to 2, i think it kinda strains the hardware

**Comment by s0faking** [comment]
hm looks like the error happens here

`2020-03-26 20:04:31.977 T:1937539648   ERROR: CCurlFile::Stat - Failed: Stream error in the HTTP/2 framing layer(92) for https://loopstreamoe3.apa.at/?shoutcast=1&player=radiothek_v1&referer=radiothek.orf.at......`

the url seems fine and also playable on my end. are you using a proxy or are you accessing the radiothek with a non austrian ip?

**Comment by DButter** [comment]
nope, its a pretty standard setup. pi to router to modem, no vpn/proxy shenanigans. i'm going to try to get cleaner logs tomorrow, the additional load really killed my pi, gonna try it on stronger hardware.

**Comment by dev-endy** [comment]
I'v got a similar problem.
When I choose "Sendung Verpasst" and navigate to any podcast I get  an error:
https://paste.kodi.tv/kobawocumi.kodi
A curl (from Chromes network analysis tool) that worked for the same Podcast:
`curl 'https://files.orf.at/podcast/oe1/mp3/OE1_journale_200327_mij.MP3' \
-H 'Sec-Fetch-Dest: video' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.149 Chrome/80.0.3987.149 Safari/537.36' \
--compressed --output test.mp3`

**Comment by s0faking** [comment]
according to the log you are trying to play the "OE1 Mittagsjournal" (27.3 - 11:59) not a podcast, podcasts are basic mp3 files served by the webserver. other streams are handled by shoutcast. in that case the url would be 

`https://loopstream01.apa.at/?shoutcast=1&player=radiothek_v1&referer=radiothek.orf.at&offset=0&id=2020-03-27_1159_tl_51_7DaysFri23_1225755.mp3&channel=oe1`

works on my end though. the error is same one that DButter is getting. Are you also using Librelec with Kodi 18.5? Also on a raspberry pi?

**Comment by DButter** [comment]
this time I've used a kodi installation on a shield, input over ui, same procedure but i used 'journal' as search term. Same result, similar logs I think

https://paste.kodi.tv/esomorodaq

**Comment by s0faking** [comment]
hm ok, so at least we got the RPI / Libreelec thing ruled out. I tested on the same setup (Shield + Kodi 18.6) and it works. i'm starting to think this is some kind of flood protection by the radiothek servers. did it work at some point today or any day?

**Comment by s0faking** [comment]
https://cloud.lowfidelity.at/index.php/s/PxnNfijZZtMCbWb

**Comment by s0faking** [comment]
the song cue track (mariah carey ;)) took a little longer but everything loaded fine in the end

**Comment by DButter** [comment]
not that I remember, maybe there is a version missmatch somewhere

**Comment by s0faking** [comment]
did you install the addon from the official repo or did you use the zip from my github page? or do you mean a kodi version mismatch

**Comment by DButter** [comment]
I installed it from the official repo, but i dont really know how kodi handles plugin updates so i thought that there could be a version missmatch

**Comment by dev-endy** [comment]
Rpi3
Libreelec: 9.2.0
Kodi: 18.5
Addon installed from repo

**Comment by s0faking** [comment]
nope. there is only one addon version for now, so that can't be the problem

**Comment by DButter** [comment]
well, then I'm out of ideas. i dont really know enough about kodi to analyze this efficiently

**Comment by s0faking** [comment]
hehe same here. let's wait a few days to rule out the flood control thing though. it might actually start working again then. would be much easier to figure out if i could reproduce this thing, but so far i had no luck

**Comment by s0faking** [comment]
i googled the curl error but the only similar error i found was here: https://forum.kodi.tv/showthread.php?tid=161375&pid=2852901#pid2852901

no fix for it though

**Comment by dev-endy** [comment]
But can you tell me why the commandline curl tool on the RPi's downloads the stream flawlessly:

`curl 'https://loopstream01.apa.at/?channel=oe1&shoutcast=0&player=radiothek_v1&referer=radiothek.orf.at&_=1585331110574&userid=e501aca4-1096-4851-986e-a5e889a9d0bf&id
=2020-03-27_1820_tl_51_7DaysFri37_1226013.mp3&offset=0&offsetende=1390568' -H 'authority: loopstream01.apa.at' -H 'sec-fetch-dest: audio' -H 'user-agent: Mozilla/5.0 (X11; Linu
x x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/80.0.3987.149 Chrome/80.0.3987.149 Safari/537.36' -H 'accept: */*' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-
mode: no-cors' -H 'referer: https://radiothek.orf.at/oe1/20200327/592506' -H 'accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' -H 'range: bytes=0-' --compressed --output t
est.mp3`
At least here on my Libreelec

**Comment by s0faking** [comment]
i wish i could ;) can you enable "component specific logging" and on "specify component-specific logging" select libCURL. Maybe we will get some useful log messages this way

**Comment by s0faking** [comment]
[plugin.audio.radiothek_debug.zip](https://github.com/s0faking/plugin.audio.radiothek/files/4396934/plugin.audio.radiothek_debug.zip)

can you try this version. i'm still unable to reproduce the issue but i did a little tweaking in the streaming url. hopefully this one does the trick :) you might need to uninstall the old addon first

**Comment by dev-endy** [comment]
Thanks for the quick reply.
Well, the tweaking got the thing working!!! 
I can play today's "Ö1 Mittagsjournal"
Here's the relevant logging output:
https://paste.kodi.tv/qewozedijo.kodi
Will do some more testing. 
Would be great to see the fix in the next release. :-)

**Comment by DButter** [comment]
https://paste.kodi.tv/amujusiwiv

here is a log with curl specific logs enabled, gonna try your new version now

**Comment by DButter** [comment]
:P are you me, that timing is incredible?

**Comment by dev-endy** [comment]
@DButter: Awesome! Right at the same time! 
Did you get the same results too when you tried @s0faking's debug version?

**Comment by DButter** [comment]
i wanted to get a curl log from the previous version out first, but im gonna try now :)

**Comment by DButter** [comment]
yup, it works like a charm

**Comment by dev-endy** [comment]
Did some more testing without any problems. Amazing
@s0faking thanks for the fix. It's the small things that make us happy these days :-)

**Comment by s0faking** [comment]
sorry for the late reply. just pushed the update with the changes from plugin.audio.radiothek_debug.zip to the official repo.

**Comment by DButter** [comment]
cool, I'm going to close this issue then :)
