### ISSUE TITLE
Ö1 in Dolby Digital (eac3)

### ISSUE THREAD

**Issue by johannesschauer97** [s0faking/plugin.audio.radiothek#2]
Since this year Ö1 is streamable in Dolby Digital 5.1 (enhanced ac3)... A suggestion for improvement...

URL for streaming: [https://oe1dd.mdn.ors.at/out/u/oe1dd/manifest.m3u8](https://oe1dd.mdn.ors.at/out/u/oe1dd/manifest.m3u8)

Information:
`Input #0, hls, from 'https://oe1dd.mdn.ors.at/out/u/oe1dd/manifest.m3u8':
  Duration: N/A, start: 52675.488533, bitrate: 256 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 281600
    Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp, 256 kb/s
    Metadata:
      variant_bitrate : 281600`

**Comment by s0faking** [comment]
thx. i will look into it

**Comment by s0faking** [comment]
a99cda6

i will try to publish this to the repo in the next few days

**Comment by johannesschauer97** [comment]
Wonderful! Thank you really much!
