### ISSUE TITLE
timeout while opening a live stream

### ISSUE THREAD

**Issue by DButter** [s0faking/plugin.audio.radiothek#5]
as the tile suggests opening live streams does not work on any of my kodi installations anymore (tested with fm4 and oe3)

logs suggets that the connection times out while connecting to the stream url

https://paste.kodi.tv/wejonanegu

**Comment by s0faking** [comment]
thx for the report. looks like the livestreams from the json data have been disabled. i'll get back to you when i find a fix for this.

**Comment by s0faking** [comment]
as suspected the pattern for the shoutcast streams changed (the ones referenced in the json files are simply not reachable anymore). the good news are that i discovered the pattern for hls (aac) streams while going trough the radiothek website. Please try d66cbd6 or 022aafd (if you are on kodi 19). checkout the addon settings. you can set the quality & protocol there now. the livestreams should work, but i will give this some testing time before i actually push this to the official repo

**Comment by DButter** [comment]
ok, Ill test it, but the earliest data Ill be able to is thuersday so itll take some time until i can give you feedback

**Comment by DButter** [comment]
https://paste.kodi.tv/ozihuvimov

so, i may be to stupid to install a plugin from a git repo. i just download the repo as zip file and install from repo right?

**Comment by s0faking** [comment]
sorry my bad. i forgot the __init__.py files for the kodi 18 version. you can use the zip files from the release page https://github.com/s0faking/plugin.audio.radiothek/releases

your method also works but you might have to rename the folder in the zip file (github always appends *-master) to the folder. if you install that you get duplicate addon folders in your kodi userdir.

**Comment by DButter** [comment]
ok, tried it live streams do indeed work with default settings now

**Comment by StefanBrand** [comment]
@s0faking I confirm that livestream does not work on my Raspberry Pi 4 on LibreELEC (Kodi 18.9). Could you push the fix to the repository?
